### ISSUE TITLE
Newer Python support

### ISSUE THREAD

**Issue by impredicative** [microamp/istruct#1]
Any plans to officially support newer Python, e.g. 3.5, 3.6?

**Comment by microamp** [comment]
Yes, sure. Since the lib is super minimal, it should, in theory, run on newer Python versions without any issues. I'll test and have it available on PyPI as soon as I can. Thanks!

**Comment by microamp** [comment]
Tried both 3.5 and 3.6 and tests still pass. Should be available on PyPI now,
```
pip install --upgrade istruct
```
